server:
  port: 8085  # 端口不能重合
hm:
  db:
    database: hm-trade
  swagger:
    title: "黑马商城交易服务接口文档"
    package: com.hmall.trade.controller
spring:
  rabbitmq:
    host: 192.168.31.128
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码
    listener:
      simple:
        prefetch: 1 #每次处理一条消息，谁处理的快谁就处理的多
        acknowledge-mode: manual # 消费者确认机制，springAMQP自动处理，若nack则再次投递消息，auto有问题服务器断电会丢失消息
        retry:
          enabled: true # 开启消费者失败重试机制，消费者异常时利用本地重试，而不是无限的requeue到mq与mq之间无限投递重试
          initial-interval: 1000ms # 失败后的初始等待时间
          multiplier: 1 # 失败后下次的等待时间倍数，下次的等待时常 = initial-interval * multiplier
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含"事务"Transactional，这里才改为false
  redis:
    host: 127.0.0.1      # 你的 Redis 服务器地址
    port: 6379           # Redis 端口
    password:            # 如果有密码填这里，没有就留空
    database: 0          # 使用的数据库索引，默认0
    lettuce:
      pool:
        max-active: 8    # 连接池最大连接数
        max-wait: -1ms   # 连接池最大阻塞等待时间
        max-idle: 8      # 连接池中的最大空闲连接
        min-idle: 0      # 连接池中的最小空闲连接
xxl:
  job:
    admin:
      # 调度中心的地址
      addresses: http://192.168.31.128:8088/xxl-job-admin
    accessToken: default_token # 如果调度中心配置了 token，这里必须保持一致
    executor:
      # 执行器名称，在调度中心配置任务时要用到
      appName: trade-service-executor
      # 执行器 IP，默认自动获取，可以为空
      address:
      # 执行器端口，如果你在一台物理机上启动多个实例，端口需要不一样 (默认9999)
      port: 9999
      # 执行器运行日志文件存储磁盘路径
      logPath: /data/applogs/xxl-job/jobhandler
      # 执行器日志文件保存天数
      logRetentionDays: 30